- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart the watcher
  community.docker.docker_compose_v2:
    project_src: "{{ hg_offline_dir }}/watcher"
    state: restarted
