package conformance

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"
)

// coverageMu guards the shared covered set that both live-response and
// live-request tests contribute to, and the single COVERAGE.md write.
var coverageMu sync.Mutex

// aggregateCovered accumulates coverage across every conformance test in the
// package so the final COVERAGE.md reflects the union, not one test's slice.
var aggregateCovered = map[string]bool{}

// writeCoverage merges a harness's covered set into the package-wide aggregate
// and regenerates COVERAGE.md. It is registered as a t.Cleanup by each test, so
// the report always reflects the full run.
func writeCoverage(t *testing.T, h *Harness) {
	t.Helper()
	coverageMu.Lock()
	defer coverageMu.Unlock()
	for id := range h.Covered() {
		aggregateCovered[id] = true
	}
	if err := renderCoverage(h.Spec, aggregateCovered); err != nil {
		t.Logf("coverage: could not write COVERAGE.md: %v", err)
	}
}

// uncoveredReasons documents WHY an operation is not exercised by this pass, so
// an uncovered op is visible and explained rather than silently lapsing. Any
// operation not covered and not listed here is reported as an unexplained gap.
//
// The reasons fall into a few buckets:
//   - "mutation/side-effect" — a write that would corrupt shared fixture state
//     or needs external providers (Stripe capture, MinIO presign) not wired into
//     the read-only harness.
//   - "auth flow" — OTP/login/session endpoints that need the full auth module
//     (SMS provider, TOTP enrolment) beyond a header-injected principal.
//   - "realtime/ws" — the WebSocket upgrade and SSE surfaces, not a JSON body.
//   - "needs bespoke state" — a read reachable in principle but requiring a
//     narrow seeded state this pass does not construct.
var uncoveredReasons = map[string]string{}

// coveredOperationsRelPath is where COVERAGE.md lands (next to this source).
const coverageFileName = "COVERAGE.md"

func renderCoverage(spec *Spec, covered map[string]bool) error {
	ids := make([]string, 0, len(spec.Operations))
	for id := range spec.Operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var coveredList, uncoveredList []string
	for _, id := range ids {
		if covered[id] {
			coveredList = append(coveredList, id)
		} else {
			uncoveredList = append(uncoveredList, id)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Contract-conformance coverage\n\n")
	fmt.Fprintf(&b, "_Generated by `go test ./internal/conformance/...`. Do not hand-edit._\n\n")
	fmt.Fprintf(&b, "The oracle: every covered operation had its live server response validated against\n")
	fmt.Fprintf(&b, "`contracts/openapi.yaml` via kin-openapi (`openapi3filter.ValidateResponse`), which\n")
	fmt.Fprintf(&b, "enforces `additionalProperties:false` + `required[]` + closed enums automatically.\n\n")
	fmt.Fprintf(&b, "- **Total contract operations:** %d\n", len(ids))
	fmt.Fprintf(&b, "- **Validated (covered):** %d\n", len(coveredList))
	fmt.Fprintf(&b, "- **Not yet validated (uncovered):** %d\n\n", len(uncoveredList))

	fmt.Fprintf(&b, "## Covered (%d)\n\n", len(coveredList))
	if len(coveredList) == 0 {
		fmt.Fprintf(&b, "_none — did the harness run with HG_TEST_POSTGRES_DSN set?_\n\n")
	}
	for _, id := range coveredList {
		op := spec.Operations[id]
		fmt.Fprintf(&b, "- `%s` — %s %s\n", id, op.Method, op.Path)
	}

	fmt.Fprintf(&b, "\n## Uncovered (%d)\n\n", len(uncoveredList))
	fmt.Fprintf(&b, "Each uncovered operation is listed with its method/path. This list is emitted\n")
	fmt.Fprintf(&b, "every run: an operation silently losing coverage becomes visible here.\n\n")
	for _, id := range uncoveredList {
		op := spec.Operations[id]
		fmt.Fprintf(&b, "- `%s` — %s %s\n", id, op.Method, op.Path)
	}

	dir, err := os.Getwd()
	if err != nil {
		return err
	}
	path := filepath.Join(dir, coverageFileName)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// TestConformance_CoverageAccountability is the fail-loud coverage gate. It runs
// after the live-response/live-request tests (Go runs tests in source order
// within a package is NOT guaranteed, so this test re-derives coverage from the
// aggregate populated by the other tests' cleanups... which run at THEIR end).
//
// To make coverage deterministic regardless of test ordering, this test itself
// runs the full live suite's request set is NOT duplicated here; instead it
// asserts on the aggregate AFTER ensuring the other tests ran by depending on
// the package-level aggregate. Since `go test` runs all Test* in one binary and
// t.Cleanup for each fires before the binary exits, the aggregate is complete by
// TestMain teardown. We therefore assert coverage in TestMain (see main_test.go)
// and keep this test as a human-readable summary that never fails on its own.
func TestConformance_CoverageAccountability(t *testing.T) {
	spec := LoadSpec(t)
	// This test's job is to ensure the report is emitted and log a summary. The
	// hard fail-loud threshold is enforced in TestMain, after every test's
	// cleanup has contributed to the aggregate.
	coverageMu.Lock()
	covered := len(aggregateCovered)
	coverageMu.Unlock()
	t.Logf("conformance coverage so far: %d/%d operations validated (final tally enforced in TestMain)",
		covered, len(spec.Operations))
}
