-- Code generated by tools/gen_enums.py from contracts/openapi.yaml. DO NOT EDIT.
--
-- Every Postgres enum below is derived mechanically from the wire contract, so
-- "the database enum agrees with the contract enum" is a property of the build
-- rather than a claim in a comment. tools/check_enums.py re-verifies it against
-- a live database in CI.
--
-- Contract enums with no persisted counterpart are listed in
-- tools/enum_map.py:EXCLUSIONS, each with a reason.

-- +goose Up

-- account_status  <-  AccountStatus
CREATE TYPE account_status AS ENUM (
  'ACTIVE',
  'SUSPENDED',
  'BANNED',
  'DELETED'
);

-- allergen_tag  <-  AllergenTag
CREATE TYPE allergen_tag AS ENUM (
  'PEANUTS',
  'TREE_NUTS',
  'SESAME',
  'MILK',
  'EGGS',
  'FISH',
  'CRUSTACEANS_MOLLUSCS',
  'SOY',
  'WHEAT_TRITICALE',
  'SULPHITES',
  'MUSTARD'
);

-- assignment_state  <-  AssignmentState
CREATE TYPE assignment_state AS ENUM (
  'ASSIGNED',
  'EN_ROUTE_TO_PICKUP',
  'ARRIVED_AT_PICKUP',
  'PICKED_UP',
  'EN_ROUTE_TO_DROPOFF',
  'ARRIVED_AT_DROPOFF',
  'DELIVERED',
  'UNDELIVERABLE',
  'RETURNING',
  'RETURNED',
  'CANCELLED_BY_PLATFORM',
  'REASSIGNED'
);

-- auth_method  <-  AuthMethod
CREATE TYPE auth_method AS ENUM (
  'otp',
  'pwd',
  'pwd+totp'
);

-- availability_resolvable_by  <-  RestaurantAvailability/properties/resolvable_by
CREATE TYPE availability_resolvable_by AS ENUM (
  'RESTAURANT',
  'ADMIN',
  'TIME'
);

-- cart_line_unavailable_reason  <-  CartLineAvailability/properties/reason
CREATE TYPE cart_line_unavailable_reason AS ENUM (
  'OUT_OF_STOCK',
  'ITEM_DELETED',
  'CATEGORY_INACTIVE',
  'RESTAURANT_CLOSED',
  'RESTAURANT_UNAVAILABLE',
  'PRICE_CHANGED',
  'VARIANT_UNAVAILABLE',
  'ADDON_UNAVAILABLE'
);

-- client_surface  <-  ClientSurface
CREATE TYPE client_surface AS ENUM (
  'customer-app',
  'rider-app',
  'restaurant-web',
  'admin-web',
  'web'
);

-- currency_code  <-  Currency
CREATE TYPE currency_code AS ENUM (
  'CAD'
);

-- customer_cancellation_reason_code  <-  CustomerCancellationReasonCode
CREATE TYPE customer_cancellation_reason_code AS ENUM (
  'ORDERED_BY_MISTAKE',
  'TOO_LONG_WAIT',
  'WRONG_ADDRESS',
  'CHANGED_MIND',
  'DUPLICATE_ORDER',
  'OTHER'
);

-- delay_reason_code  <-  DelayReasonCode
CREATE TYPE delay_reason_code AS ENUM (
  'HIGH_VOLUME',
  'INGREDIENT_PREP',
  'EQUIPMENT_ISSUE',
  'STAFF_SHORTAGE',
  'ORDER_COMPLEXITY',
  'OTHER'
);

-- delivery_instruction  <-  DeliveryInstruction
CREATE TYPE delivery_instruction AS ENUM (
  'LEAVE_AT_DOOR',
  'DO_NOT_RING_BELL',
  'DO_NOT_CALL',
  'MEET_AT_DOOR',
  'MEET_IN_LOBBY'
);

-- device_platform  <-  DevicePlatform
CREATE TYPE device_platform AS ENUM (
  'ios',
  'android',
  'web'
);

-- dietary_tag  <-  DietaryTag
CREATE TYPE dietary_tag AS ENUM (
  'VEGETARIAN',
  'VEGAN',
  'GLUTEN_FREE',
  'DAIRY_FREE',
  'NUT_FREE',
  'HALAL_CERTIFIED',
  'SPICY',
  'KETO',
  'LOW_CARB'
);

-- discount_funded_by  <-  DiscountFundedBy
CREATE TYPE discount_funded_by AS ENUM (
  'PLATFORM',
  'RESTAURANT'
);

-- discount_target  <-  DiscountTarget
CREATE TYPE discount_target AS ENUM (
  'ITEMS',
  'DELIVERY_FEE',
  'SERVICE_FEE'
);

-- dispatch_offer_outcome  <-  DispatchOfferOutcome
CREATE TYPE dispatch_offer_outcome AS ENUM (
  'ACCEPTED',
  'REJECTED',
  'EXPIRED',
  'WITHDRAWN'
);

-- dispatch_state  <-  DispatchState
CREATE TYPE dispatch_state AS ENUM (
  'PENDING',
  'SEARCHING',
  'OFFERED',
  'ASSIGNED',
  'AT_RESTAURANT',
  'CARRYING',
  'AT_CUSTOMER',
  'COMPLETED',
  'UNASSIGNED',
  'NO_RIDER_FOUND'
);

-- document_rejection_reason_code  <-  DocumentRejectionReasonCode
CREATE TYPE document_rejection_reason_code AS ENUM (
  'ILLEGIBLE',
  'EXPIRED',
  'WRONG_DOCUMENT_TYPE',
  'NAME_MISMATCH',
  'DOB_MISMATCH',
  'ADDRESS_MISMATCH',
  'PLATE_MISMATCH',
  'UNRECOGNISED_CERTIFIER',
  'SUSPECTED_FORGERY',
  'SUSPECTED_ALTERATION',
  'INCOMPLETE_PAGES',
  'OTHER'
);

-- earning_entry_status  <-  EarningEntryStatus
CREATE TYPE earning_entry_status AS ENUM (
  'PENDING',
  'AVAILABLE',
  'PAID',
  'REVERSED'
);

-- earning_entry_type  <-  EarningEntryType
CREATE TYPE earning_entry_type AS ENUM (
  'DELIVERY',
  'TIP',
  'CANCELLATION_COMPENSATION',
  'BONUS',
  'ADJUSTMENT',
  'CLAWBACK'
);

-- earnings_period  <-  EarningsPeriod
CREATE TYPE earnings_period AS ENUM (
  'DAY',
  'WEEK',
  'MONTH'
);

-- feed_section_key  <-  FeedSection/properties/key
CREATE TYPE feed_section_key AS ENUM (
  'order_again',
  'restaurants_near_you',
  'trending_in_your_area',
  'your_favourite_restaurants',
  'popular_items',
  'you_might_like'
);

-- fulfilment  <-  Fulfilment
CREATE TYPE fulfilment AS ENUM (
  'DELIVERY',
  'PICKUP'
);

-- halal_certificate_scope  <-  HalalCertificateScope
CREATE TYPE halal_certificate_scope AS ENUM (
  'WHOLE_ESTABLISHMENT',
  'KITCHEN_ONLY',
  'SPECIFIC_MENU_ITEMS',
  'SUPPLIER_CHAIN_ONLY'
);

-- halal_certificate_status  <-  HalalCertificateStatus
CREATE TYPE halal_certificate_status AS ENUM (
  'PENDING',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
  'REVOKED',
  'SUPERSEDED'
);

-- halal_check_key  <-  HalalCheckKey
CREATE TYPE halal_check_key AS ENUM (
  'H1_LEGIBLE_COMPLETE',
  'H2_ISSUER_ACCEPTED',
  'H3_NAME_MATCH',
  'H4_ADDRESS_MATCH',
  'H5_DATES_VALID',
  'H6_SCOPE_SUFFICIENT',
  'H7_UNIQUE_NOT_REUSED'
);

-- halal_check_result  <-  HalalCheckResult
CREATE TYPE halal_check_result AS ENUM (
  'PASS',
  'FAIL',
  'NOT_ASSESSED'
);

-- halal_display_state  <-  HalalDisplayState
CREATE TYPE halal_display_state AS ENUM (
  'CERTIFIED',
  'EXPIRING_SOON',
  'EXPIRED',
  'UNVERIFIED'
);

-- halal_issuing_body_status  <-  HalalIssuingBodyStatus
CREATE TYPE halal_issuing_body_status AS ENUM (
  'PROPOSED',
  'ACCEPTED',
  'SUSPENDED',
  'RETIRED',
  'REJECTED'
);

-- halal_rejection_reason_code  <-  HalalRejectionReasonCode
CREATE TYPE halal_rejection_reason_code AS ENUM (
  'ILLEGIBLE',
  'EXPIRED_OR_EXPIRING',
  'ISSUER_NOT_ACCEPTED',
  'NAME_MISMATCH',
  'ADDRESS_MISMATCH',
  'SCOPE_INSUFFICIENT',
  'DUPLICATE_CERTIFICATE',
  'SUSPECTED_FORGERY',
  'OTHER'
);

-- handover_method  <-  HandoverMethod
CREATE TYPE handover_method AS ENUM (
  'HANDED_TO_CUSTOMER',
  'LEFT_AT_DOOR',
  'LEFT_WITH_RECEPTION',
  'HANDED_TO_OTHER_PERSON'
);

-- kyc_document_state  <-  KycDocumentState
CREATE TYPE kyc_document_state AS ENUM (
  'SUBMITTED',
  'IN_REVIEW',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
  'SUPERSEDED'
);

-- kyc_subject_type  <-  KycDocument/properties/subject_type
CREATE TYPE kyc_subject_type AS ENUM (
  'RESTAURANT',
  'RIDER'
);

-- ledger_account  <-  LedgerAccount
CREATE TYPE ledger_account AS ENUM (
  'CUSTOMER_CHARGES',
  'PSP_CLEARING',
  'PSP_FEES',
  'RESTAURANT_PAYABLE',
  'RIDER_PAYABLE',
  'PLATFORM_REVENUE',
  'TAX_PAYABLE',
  'PROMO_EXPENSE',
  'REFUNDS',
  'PLATFORM_ABSORBED'
);

-- ledger_batch_kind  <-  LedgerEntry/properties/batch_kind
CREATE TYPE ledger_batch_kind AS ENUM (
  'CAPTURE',
  'SETTLE',
  'REFUND',
  'PAYOUT',
  'ADJUSTMENT',
  'PSP_FEE'
);

-- ledger_component  <-  LedgerComponent
CREATE TYPE ledger_component AS ENUM (
  'SUBTOTAL',
  'COMMISSION',
  'DELIVERY_FEE',
  'SERVICE_FEE',
  'TAX',
  'TIP',
  'DISCOUNT',
  'PSP_FEE',
  'REFUND'
);

-- ledger_counterparty_type  <-  LedgerEntry/properties/counterparty_type
CREATE TYPE ledger_counterparty_type AS ENUM (
  'RESTAURANT',
  'RIDER',
  'CUSTOMER',
  'PLATFORM',
  'CRA'
);

-- locale_code  <-  Principal/properties/locale
CREATE TYPE locale_code AS ENUM (
  'en-CA',
  'fr-CA'
);

-- menu_item_availability_state  <-  MenuItemAvailabilityState
CREATE TYPE menu_item_availability_state AS ENUM (
  'AVAILABLE',
  'OUT_OF_STOCK',
  'HIDDEN',
  'BLOCKED'
);

-- menu_rejection_reason_code  <-  MenuRejectionReasonCode
CREATE TYPE menu_rejection_reason_code AS ENUM (
  'MISLEADING_DESCRIPTION',
  'UNSUBSTANTIATED_HALAL_CLAIM',
  'INCORRECT_DIETARY_TAG',
  'MISSING_ALLERGEN',
  'POOR_IMAGE_QUALITY',
  'IMAGE_NOT_OF_DISH',
  'PROHIBITED_ITEM',
  'OFFENSIVE_CONTENT',
  'OTHER'
);

-- menu_review_status  <-  MenuReviewStatus
CREATE TYPE menu_review_status AS ENUM (
  'DRAFT',
  'PENDING_REVIEW',
  'APPROVED',
  'REJECTED',
  'WITHDRAWN',
  'SUPERSEDED'
);

-- next_route  <-  NextRoute
CREATE TYPE next_route AS ENUM (
  'HOME',
  'PROFILE_CAPTURE',
  'ONBOARDING_PROFILE',
  'ONBOARDING_VEHICLE',
  'ONBOARDING_DOCUMENTS',
  'ONBOARDING_AWAITING_REVIEW',
  'ONBOARDING_REJECTED',
  'ONBOARDING_PAYOUT',
  'ONBOARDING_MENU',
  'ACTIVE_DELIVERY',
  'ORDER_TRACKING',
  'SUSPENDED',
  'APP_UPDATE_REQUIRED'
);

-- notification_channel  <-  NotificationChannel
CREATE TYPE notification_channel AS ENUM (
  'REALTIME',
  'PUSH',
  'SMS',
  'EMAIL',
  'INAPP'
);

-- notification_priority  <-  NotificationPriority
CREATE TYPE notification_priority AS ENUM (
  'CRITICAL',
  'HIGH',
  'NORMAL',
  'LOW'
);

-- offer_reject_reason_code  <-  OfferRejectReasonCode
CREATE TYPE offer_reject_reason_code AS ENUM (
  'TOO_FAR',
  'TOO_FAR_PICKUP',
  'TOO_FAR_DROPOFF',
  'TOO_LONG_WAIT',
  'EARNINGS_TOO_LOW',
  'VEHICLE_UNSUITABLE',
  'RESTAURANT_TOO_SLOW',
  'ENDING_SHIFT',
  'PERSONAL_BREAK',
  'SAFETY_CONCERN',
  'ORDER_TOO_LARGE',
  'OTHER'
);

-- offer_state  <-  OfferState
CREATE TYPE offer_state AS ENUM (
  'PENDING',
  'ACCEPTED',
  'REJECTED',
  'EXPIRED',
  'WITHDRAWN'
);

-- order_actor_kind  <-  OrderActorKind
CREATE TYPE order_actor_kind AS ENUM (
  'CUSTOMER',
  'RESTAURANT',
  'RIDER',
  'SUPPORT',
  'ADMIN',
  'SYSTEM'
);

-- order_cancellation_reason_code  <-  OrderCancellationReasonCode
CREATE TYPE order_cancellation_reason_code AS ENUM (
  'CUSTOMER_CANCELLED',
  'RESTAURANT_TIMEOUT',
  'RESTAURANT_CLOSED',
  'ITEM_UNAVAILABLE',
  'CAPTURE_FAILED',
  'PAYMENT_EXPIRED',
  'PREP_OVERDUE',
  'NO_RIDER_FOUND',
  'SUPPORT_CANCELLED',
  'FRAUD_SUSPECTED',
  'PLATFORM_ERROR'
);

-- order_state  <-  OrderState
CREATE TYPE order_state AS ENUM (
  'CREATED',
  'AUTHORIZED',
  'RESTAURANT_PENDING',
  'PREPARING',
  'READY_FOR_PICKUP',
  'PICKED_UP',
  'ARRIVED',
  'DELIVERED',
  'COMPLETED',
  'CANCELLED',
  'REJECTED',
  'FAILED',
  'DISPUTED',
  'RESOLVED'
);

-- order_status_group  <-  OrderStatusGroup
CREATE TYPE order_status_group AS ENUM (
  'ACTIVE',
  'PAST'
);

-- otp_purpose  <-  OtpRequestInput/properties/purpose
CREATE TYPE otp_purpose AS ENUM (
  'SIGN_IN',
  'PHONE_CHANGE',
  'STEP_UP'
);

-- payment_intent_kind  <-  PaymentIntentKind
CREATE TYPE payment_intent_kind AS ENUM (
  'ORDER',
  'POST_DELIVERY_TIP',
  'ADJUSTMENT'
);

-- payment_state  <-  PaymentState
CREATE TYPE payment_state AS ENUM (
  'REQUIRES_PAYMENT_METHOD',
  'REQUIRES_CONFIRMATION',
  'REQUIRES_ACTION',
  'PROCESSING',
  'REQUIRES_CAPTURE',
  'SUCCEEDED',
  'CANCELED',
  'FAILED'
);

-- payout_interval  <-  PayoutInterval
CREATE TYPE payout_interval AS ENUM (
  'DAILY',
  'WEEKLY'
);

-- payout_state  <-  PayoutState
CREATE TYPE payout_state AS ENUM (
  'DRAFT',
  'READY',
  'TRANSFERRING',
  'TRANSFERRED',
  'PAID',
  'FAILED',
  'HELD'
);

-- pod_method  <-  PodMethod
CREATE TYPE pod_method AS ENUM (
  'OTP',
  'PHOTO',
  'PHOTO_WITH_ATTESTATION'
);

-- price_band  <-  PriceBand
CREATE TYPE price_band AS ENUM (
  '$',
  '$$',
  '$$$',
  '$$$$'
);

-- province  <-  Province
CREATE TYPE province AS ENUM (
  'AB',
  'BC',
  'MB',
  'NB',
  'NL',
  'NS',
  'NT',
  'NU',
  'ON',
  'PE',
  'QC',
  'SK',
  'YT'
);

-- refund_kind  <-  RefundKind
CREATE TYPE refund_kind AS ENUM (
  'FULL',
  'PARTIAL_ITEMS',
  'FEES_ONLY',
  'GOODWILL'
);

-- refund_reason_code  <-  RefundReasonCode
CREATE TYPE refund_reason_code AS ENUM (
  'RESTAURANT_REJECTED',
  'ITEM_MISSING',
  'MISSING_ITEMS',
  'WRONG_ITEM',
  'WRONG_ITEMS',
  'FOOD_QUALITY',
  'FOOD_SAFETY',
  'NEVER_DELIVERED',
  'ORDER_NEVER_ARRIVED',
  'LATE_DELIVERY',
  'WRONG_ADDRESS',
  'DAMAGED_SPILLED',
  'NO_RIDER_FOUND',
  'CUSTOMER_CHANGED_MIND',
  'RESTAURANT_CANCELLED',
  'PLATFORM_INITIATED_CANCELLATION',
  'PLATFORM_ERROR',
  'DUPLICATE_CHARGE',
  'CHARGED_INCORRECTLY',
  'PRICING_ERROR',
  'HALAL_CONCERN',
  'HALAL_INTEGRITY',
  'GOODWILL',
  'DISPUTE_RESOLUTION',
  'CHARGEBACK_PREEMPTIVE',
  'OTHER'
);

-- refund_scope  <-  RefundScope
CREATE TYPE refund_scope AS ENUM (
  'FULL',
  'PARTIAL_ITEMS',
  'PARTIAL_AMOUNT'
);

-- refund_state  <-  RefundState
CREATE TYPE refund_state AS ENUM (
  'REQUESTED',
  'PENDING_APPROVAL',
  'APPROVED',
  'AUTHORISED',
  'SUBMITTED',
  'SUCCEEDED',
  'SETTLED',
  'FAILED',
  'DECLINED',
  'CANCELLED'
);

-- remittable_by  <-  RemittableBy
CREATE TYPE remittable_by AS ENUM (
  'PLATFORM',
  'RESTAURANT'
);

-- restaurant_account_state  <-  RestaurantAccountState
CREATE TYPE restaurant_account_state AS ENUM (
  'PENDING',
  'LIVE',
  'DELISTED',
  'SUSPENDED',
  'BANNED',
  'DEACTIVATED',
  'CLOSED'
);

-- restaurant_approve_reason_code  <-  RestaurantApproveReasonCode
CREATE TYPE restaurant_approve_reason_code AS ENUM (
  'ALL_CHECKS_PASSED',
  'APPROVED_WITH_NOTES'
);

-- restaurant_availability_state  <-  RestaurantAvailabilityState
CREATE TYPE restaurant_availability_state AS ENUM (
  'OPEN',
  'CLOSED_HOURS',
  'PAUSED',
  'OUT_OF_RANGE',
  'NO_ADDRESS'
);

-- restaurant_decision  <-  RestaurantDecision
CREATE TYPE restaurant_decision AS ENUM (
  'APPROVE',
  'REQUEST_CHANGES',
  'REJECT'
);

-- restaurant_doc_type  <-  RestaurantDocType
CREATE TYPE restaurant_doc_type AS ENUM (
  'BUSINESS_LICENCE',
  'HALAL_CERTIFICATE',
  'FOOD_SAFETY',
  'OWNER_ID',
  'LIABILITY_INSURANCE'
);

-- restaurant_onboarding_state  <-  RestaurantOnboardingState
CREATE TYPE restaurant_onboarding_state AS ENUM (
  'REGISTERED',
  'EMAIL_VERIFIED',
  'PROFILE_PENDING',
  'DOCUMENTS_PENDING',
  'DOCUMENTS_REVIEW',
  'DOCUMENTS_APPROVED',
  'DOCUMENTS_REJECTED',
  'PAYOUT_PENDING',
  'MENU_PENDING',
  'ACTIVE',
  'WITHDRAWN'
);

-- restaurant_onboarding_step  <-  RestaurantOnboardingStatus/properties/current_step
CREATE TYPE restaurant_onboarding_step AS ENUM (
  'PROFILE',
  'DOCUMENTS',
  'AWAITING_REVIEW',
  'FIX_DOCUMENTS',
  'PAYOUT',
  'MENU',
  'DONE'
);

-- restaurant_open_state  <-  RestaurantOpenState
CREATE TYPE restaurant_open_state AS ENUM (
  'OPEN',
  'PAUSED',
  'CLOSED_HOURS',
  'CLOSED_HOLIDAY',
  'CLOSED_TOGGLE',
  'CLOSED_OFFLINE',
  'CLOSED_SUSPENDED'
);

-- restaurant_reject_application_reason_code  <-  RestaurantRejectApplicationReasonCode
CREATE TYPE restaurant_reject_application_reason_code AS ENUM (
  'HALAL_CERTIFICATION_INVALID',
  'DOCUMENTS_INSUFFICIENT',
  'IDENTITY_UNVERIFIED',
  'OUTSIDE_SERVICE_AREA',
  'PROHIBITED_CUISINE_OR_PRODUCT',
  'SUSPECTED_FRAUD',
  'DUPLICATE_APPLICATION',
  'WITHDRAWN_BY_APPLICANT',
  'OTHER'
);

-- restaurant_reject_reason_code  <-  RestaurantRejectReasonCode
CREATE TYPE restaurant_reject_reason_code AS ENUM (
  'ITEM_UNAVAILABLE',
  'KITCHEN_AT_CAPACITY',
  'CLOSING_SOON',
  'EQUIPMENT_FAILURE',
  'ADDRESS_OUT_OF_RANGE',
  'SUSPECTED_FRAUD',
  'OTHER'
);

-- restaurant_sort  <-  RestaurantSort
CREATE TYPE restaurant_sort AS ENUM (
  'RECOMMENDED',
  'RATING_DESC',
  'ETA_ASC',
  'DISTANCE_ASC'
);

-- rider_account_status  <-  RiderAccountStatus
CREATE TYPE rider_account_status AS ENUM (
  'PENDING',
  'ACTIVE',
  'SUSPENDED',
  'DEACTIVATED'
);

-- rider_availability_state  <-  RiderAvailabilityState
CREATE TYPE rider_availability_state AS ENUM (
  'OFFLINE',
  'ONLINE_IDLE',
  'ONLINE_STALE',
  'ON_DELIVERY'
);

-- rider_blocking_reason  <-  RiderAvailability/properties/blocking_reasons/items
CREATE TYPE rider_blocking_reason AS ENUM (
  'ONBOARDING_INCOMPLETE',
  'ACCOUNT_NOT_ACTIVE',
  'PAYOUT_ACCOUNT_INCOMPLETE',
  'FOREGROUND_LOCATION_PERMISSION',
  'BACKGROUND_LOCATION_PERMISSION',
  'NOTIFICATION_PERMISSION',
  'STALE_LOCATION_FIX',
  'DOCUMENT_EXPIRED',
  'CONTINUOUS_ONLINE_CAP'
);

-- rider_doc_type  <-  RiderDocType
CREATE TYPE rider_doc_type AS ENUM (
  'DRIVERS_LICENCE',
  'VEHICLE_REGISTRATION',
  'VEHICLE_INSURANCE',
  'GOVERNMENT_ID',
  'WORK_ELIGIBILITY',
  'PROFILE_PHOTO'
);

-- rider_onboarding_state  <-  RiderOnboardingState
CREATE TYPE rider_onboarding_state AS ENUM (
  'REGISTERED',
  'PHONE_VERIFIED',
  'PROFILE_PENDING',
  'VEHICLE_PENDING',
  'DOCUMENTS_PENDING',
  'DOCUMENTS_REVIEW',
  'DOCUMENTS_APPROVED',
  'DOCUMENTS_REJECTED',
  'PAYOUT_PENDING',
  'ACTIVE'
);

-- rider_onboarding_step  <-  RiderOnboardingStatus/properties/next_step
CREATE TYPE rider_onboarding_step AS ENUM (
  'PROFILE',
  'VEHICLE',
  'DOCUMENTS',
  'AWAITING_REVIEW',
  'FIX_DOCUMENTS',
  'PAYOUT',
  'DONE'
);

-- rider_position_reject_code  <-  RiderPositionAck/properties/rejected/items/properties/code
CREATE TYPE rider_position_reject_code AS ENUM (
  'STALE_POINT',
  'FUTURE_POINT',
  'LOW_ACCURACY'
);

-- role_name  <-  Role
CREATE TYPE role_name AS ENUM (
  'CUSTOMER',
  'RIDER',
  'RESTAURANT_OWNER',
  'RESTAURANT_MANAGER',
  'RESTAURANT_STAFF',
  'SUPPORT_AGENT',
  'ADMIN',
  'SUPER_ADMIN'
);

-- role_scope_type  <-  RoleGrant/properties/scope_type
CREATE TYPE role_scope_type AS ENUM (
  'GLOBAL',
  'RESTAURANT'
);

-- route_source  <-  RouteSource
CREATE TYPE route_source AS ENUM (
  'ROUTED',
  'CACHED',
  'FALLBACK'
);

-- sms_sender_check_state  <-  SmsSenderCheckState
CREATE TYPE sms_sender_check_state AS ENUM (
  'PASSED',
  'FAILED',
  'NOT_CHECKED'
);

-- staff_status  <-  StaffStatus
CREATE TYPE staff_status AS ENUM (
  'INVITED',
  'ACTIVE',
  'SUSPENDED',
  'DEACTIVATED'
);

-- stored_object_purpose  <-  StoredObjectPurpose
CREATE TYPE stored_object_purpose AS ENUM (
  'KYC_DOCUMENT',
  'MENU_IMAGE',
  'POD',
  'AVATAR',
  'EXPORT'
);

-- stored_object_state  <-  StoredObjectState
CREATE TYPE stored_object_state AS ENUM (
  'PENDING',
  'READY',
  'REJECTED',
  'DELETED'
);

-- tax_category  <-  TaxCategory
CREATE TYPE tax_category AS ENUM (
  'PREPARED_FOOD',
  'ZERO_RATED_GROCERY',
  'BEVERAGE_ALCOHOL',
  'DELIVERY',
  'SERVICE_FEE',
  'COMMISSION'
);

-- tax_kind  <-  TaxKind
CREATE TYPE tax_kind AS ENUM (
  'GST',
  'HST',
  'QST',
  'PST',
  'RST',
  'HST_FEDERAL_PART'
);

-- tracking_health  <-  TrackingHealth
CREATE TYPE tracking_health AS ENUM (
  'HEALTHY',
  'DEGRADED',
  'LOST'
);

-- variant_pricing_mode  <-  VariantPricingMode
CREATE TYPE variant_pricing_mode AS ENUM (
  'ABSOLUTE',
  'DELTA'
);

-- vehicle_type  <-  VehicleType
CREATE TYPE vehicle_type AS ENUM (
  'CAR',
  'SCOOTER',
  'MOTORCYCLE',
  'BICYCLE',
  'ON_FOOT'
);

-- waitlist_audience  <-  WaitlistAudience
CREATE TYPE waitlist_audience AS ENUM (
  'CUSTOMER',
  'RESTAURANT',
  'RIDER'
);

-- waitlist_contact_kind  <-  WaitlistContactKind
CREATE TYPE waitlist_contact_kind AS ENUM (
  'EMAIL',
  'TEL'
);


-- +goose Down

DROP TYPE IF EXISTS waitlist_contact_kind;
DROP TYPE IF EXISTS waitlist_audience;
DROP TYPE IF EXISTS vehicle_type;
DROP TYPE IF EXISTS variant_pricing_mode;
DROP TYPE IF EXISTS tracking_health;
DROP TYPE IF EXISTS tax_kind;
DROP TYPE IF EXISTS tax_category;
DROP TYPE IF EXISTS stored_object_state;
DROP TYPE IF EXISTS stored_object_purpose;
DROP TYPE IF EXISTS staff_status;
DROP TYPE IF EXISTS sms_sender_check_state;
DROP TYPE IF EXISTS route_source;
DROP TYPE IF EXISTS role_scope_type;
DROP TYPE IF EXISTS role_name;
DROP TYPE IF EXISTS rider_position_reject_code;
DROP TYPE IF EXISTS rider_onboarding_step;
DROP TYPE IF EXISTS rider_onboarding_state;
DROP TYPE IF EXISTS rider_doc_type;
DROP TYPE IF EXISTS rider_blocking_reason;
DROP TYPE IF EXISTS rider_availability_state;
DROP TYPE IF EXISTS rider_account_status;
DROP TYPE IF EXISTS restaurant_sort;
DROP TYPE IF EXISTS restaurant_reject_reason_code;
DROP TYPE IF EXISTS restaurant_reject_application_reason_code;
DROP TYPE IF EXISTS restaurant_open_state;
DROP TYPE IF EXISTS restaurant_onboarding_step;
DROP TYPE IF EXISTS restaurant_onboarding_state;
DROP TYPE IF EXISTS restaurant_doc_type;
DROP TYPE IF EXISTS restaurant_decision;
DROP TYPE IF EXISTS restaurant_availability_state;
DROP TYPE IF EXISTS restaurant_approve_reason_code;
DROP TYPE IF EXISTS restaurant_account_state;
DROP TYPE IF EXISTS remittable_by;
DROP TYPE IF EXISTS refund_state;
DROP TYPE IF EXISTS refund_scope;
DROP TYPE IF EXISTS refund_reason_code;
DROP TYPE IF EXISTS refund_kind;
DROP TYPE IF EXISTS province;
DROP TYPE IF EXISTS price_band;
DROP TYPE IF EXISTS pod_method;
DROP TYPE IF EXISTS payout_state;
DROP TYPE IF EXISTS payout_interval;
DROP TYPE IF EXISTS payment_state;
DROP TYPE IF EXISTS payment_intent_kind;
DROP TYPE IF EXISTS otp_purpose;
DROP TYPE IF EXISTS order_status_group;
DROP TYPE IF EXISTS order_state;
DROP TYPE IF EXISTS order_cancellation_reason_code;
DROP TYPE IF EXISTS order_actor_kind;
DROP TYPE IF EXISTS offer_state;
DROP TYPE IF EXISTS offer_reject_reason_code;
DROP TYPE IF EXISTS notification_priority;
DROP TYPE IF EXISTS notification_channel;
DROP TYPE IF EXISTS next_route;
DROP TYPE IF EXISTS menu_review_status;
DROP TYPE IF EXISTS menu_rejection_reason_code;
DROP TYPE IF EXISTS menu_item_availability_state;
DROP TYPE IF EXISTS locale_code;
DROP TYPE IF EXISTS ledger_counterparty_type;
DROP TYPE IF EXISTS ledger_component;
DROP TYPE IF EXISTS ledger_batch_kind;
DROP TYPE IF EXISTS ledger_account;
DROP TYPE IF EXISTS kyc_subject_type;
DROP TYPE IF EXISTS kyc_document_state;
DROP TYPE IF EXISTS handover_method;
DROP TYPE IF EXISTS halal_rejection_reason_code;
DROP TYPE IF EXISTS halal_issuing_body_status;
DROP TYPE IF EXISTS halal_display_state;
DROP TYPE IF EXISTS halal_check_result;
DROP TYPE IF EXISTS halal_check_key;
DROP TYPE IF EXISTS halal_certificate_status;
DROP TYPE IF EXISTS halal_certificate_scope;
DROP TYPE IF EXISTS fulfilment;
DROP TYPE IF EXISTS feed_section_key;
DROP TYPE IF EXISTS earnings_period;
DROP TYPE IF EXISTS earning_entry_type;
DROP TYPE IF EXISTS earning_entry_status;
DROP TYPE IF EXISTS document_rejection_reason_code;
DROP TYPE IF EXISTS dispatch_state;
DROP TYPE IF EXISTS dispatch_offer_outcome;
DROP TYPE IF EXISTS discount_target;
DROP TYPE IF EXISTS discount_funded_by;
DROP TYPE IF EXISTS dietary_tag;
DROP TYPE IF EXISTS device_platform;
DROP TYPE IF EXISTS delivery_instruction;
DROP TYPE IF EXISTS delay_reason_code;
DROP TYPE IF EXISTS customer_cancellation_reason_code;
DROP TYPE IF EXISTS currency_code;
DROP TYPE IF EXISTS client_surface;
DROP TYPE IF EXISTS cart_line_unavailable_reason;
DROP TYPE IF EXISTS availability_resolvable_by;
DROP TYPE IF EXISTS auth_method;
DROP TYPE IF EXISTS assignment_state;
DROP TYPE IF EXISTS allergen_tag;
DROP TYPE IF EXISTS account_status;
