// Package notify owns every message the platform sends outside its own UI:
// SMS, push, email and the persisted in-app inbox, plus the phone-OTP seam
// auth calls into.
//
// # The load-bearing decision
//
// A notification is a row first and a delivery attempt second (P-24). This
// package makes that true by construction: Enqueue never runs on its own
// connection — it takes the caller's *pgx.Tx and writes the `notification`
// row and a River job in that same transaction. Commit the business
// transaction (accept the order, capture the payment, cancel the delivery)
// and the notification is *guaranteed* queued; roll it back and no job, no
// row, no message ever existed. There is no code path that can capture money
// and silently fail to tell anyone, and no code path that can alarm a rider
// about an order that never actually got created.
//
// River (github.com/riverqueue/river) is the transactional-outbox engine:
// river.Client.InsertTx enqueues inside the caller's pgx.Tx using the
// riverpgxv5 driver, exactly like the realtime module's hand-rolled
// outbox_message table but with retry/backoff, uniqueness and a worker pool
// already solved. River's own tables (river_job, river_queue, river_leader,
// river_migration) are vendored as a goose migration —
// services/hg/migrations/00024_river_outbox.sql — generated by `river
// migrate-get`, not hand-written.
//
// # Why Postgres, never Redis
//
// G-1 (CLAUDE.md): flush Redis at any moment and the system must still be
// correct, only slower. A notification queue is exactly the kind of state
// that must survive that flush — an OTP code or a "your order was accepted"
// push cannot simply vanish because the cache was recycled. So the queue,
// the delivery ledger and the dedupe key all live in Postgres
// (services/hg/migrations/00020_notifications.sql: notification,
// notification_delivery, device, email_suppression). Redis is not imported by
// this package at all.
//
// # At-least-once, idempotent, multi-channel, failover
//
//   - At-least-once: River retries a job that returns an error, with
//     exponential backoff, until MaxAttempts. A job that panics or the process
//     that crashes mid-delivery leaves the job `available` or `retryable` —
//     never silently lost.
//   - Idempotent enqueue: `notification_dedupe` is a partial unique index on
//     (account_id, dedupe_key). Enqueue is `INSERT ... ON CONFLICT DO NOTHING
//     RETURNING id`; calling it twice with the same dedupe_key (e.g. a
//     goroutine retried after an ambiguous network error) produces one row and
//     one job, not two pushes.
//   - Idempotent delivery: every provider call carries the notification id
//     (plus channel) as an idempotency/client-reference key so a retried job
//     that actually succeeded upstream does not double-charge an SMS budget or
//     double-buzz a phone. Fakes and the interface both carry this key.
//   - Multi-channel with failover: Notifier tries a notification's channel
//     plan in priority order (e.g. PUSH then SMS for a HIGH-priority order
//     event) and records one notification_delivery row per attempt. The INAPP
//     row always exists regardless of push outcome — the inbox in
//     GET /v1/notifications is the system of record, push is an optimisation
//     (contract description on listNotifications).
//
// # The OTP seam
//
// Package auth (P-02) does not talk to Twilio. It calls notify.SendOTP, which
// enqueues an SMS-only, must_reach notification through the same outbox. This
// is "generalizing the SMSSender seam" from the brief: OTP is not a special
// code path, it is the SMS channel of the same Notifier every order-lifecycle
// event uses, with one deliberate exception — the persisted `notification.body`
// never contains the code (contract: Notification.body "Never contains an
// OTP code, a full address, card details or a token"). The code travels only
// in the River job's args, which are not the contract-visible inbox.
//
// # Email
//
// Email templates are written in React Email (packages/emails) and exported
// to static HTML and plain text with {{.Var}} slots, committed under
// emailtmpl/templates and embedded in the binary; no Node runs in production.
// A builder (messages.go) names a template and fills its display values
// (EmailSpec, kept in notification.data); a single-use link token travels
// only in the job (ChannelOverride.LinkToken). The worker renders the email
// just before sending (email.go), so a retried job sends byte-for-byte the
// same request.
//
// Delivery is Resend (senders.go, ResendSender), the one approved hosted
// email provider. Every request carries "<notification id>:EMAIL" as
// Resend's idempotency key, and the notification's lease (Repo.ClaimLease)
// keeps two runs of one job from overlapping, so an email is sent once per
// notification however often River runs its job. Outside production every
// email passes AllowListSender first: an address not on HG_EMAIL_ALLOWLIST is
// logged and recorded SUPPRESSED, never sent (issue #235). With no Resend key
// the LogEmailSender records each email in the log instead.
//
// What an email may contain is narrow on purpose. Every recipient is parsed
// once (CanonicalEmail) and that one canonical address is both checked
// against the allow-list and sent, so no display name, comment, list or line
// break can make the two disagree. Names someone typed (a restaurant, a
// rider, a certifying body) pass through SafeName, which strips anything
// link-like and caps the length; free text typed by staff (an admin's reason,
// an invitee's name) never goes into an email at all, only into the in-app
// inbox. The renderer refuses an email that links anywhere but the configured
// web apps (Links.onlyOurs).
//
// EMAIL is not part of the failover chain: it is always attempted for the
// kinds that plan it, beside push and SMS (P-24's fallback ladder: "EMAIL is
// always sent for its listed events regardless of socket state").
//
// # Halal invariants that touch this package
//
// This package renders no halal state and must not invent one. Order-event
// notification bodies quote fields the caller already computed (accepted
// order id, restaurant name); they never derive or restate a certification
// status, and they carry no colour — SMS and push have none, and the INAPP
// row is plain text for the client to theme. See CLAUDE.md invariants 8-10.
//
// # What this package does not own
//
// Repository ownership checks (P-07: GetOrderFor, never GetOrder) belong to
// the callers that hand this package an account id. This package trusts the
// account_id it is given; it is the caller's job to have proven the principal
// owns that account. Device registration (POST/DELETE on device rows) and the
// two contract-visible endpoints — GET /v1/notifications, POST
// /v1/notifications/{id}/read — are tagged `accounts` in the contract and are
// expected to be thin handlers over Repo.ListInbox / Repo.MarkRead here; they
// are not wired into httpx.Router in this change (no router exists yet for
// this isolated module build) but the repository methods they need are ready.
//
// Spec: docs/spec/01-platform.md, "P-24 — Notification router" (the
// router matrix), "P-25 — Push notifications (Expo)" and "P-26 — SMS and
// email" (channels and suppression).
package notify
