#!/usr/bin/env python3
"""
Generate migrations/00002_enums.sql from contracts/openapi.yaml.

The enum migration is generated, never hand-edited, so a contract enum and its
Postgres type cannot drift. Re-run after any contract change; the diff is the
review.

    python3 tools/gen_enums.py > 00002_enums.sql
"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from enum_map import MAPPED, MAPPED_IN_MIGRATION, EXCLUSIONS          # noqa: E402
from openapi_enums import contract_enums         # noqa: E402

HEADER = """-- Code generated by tools/gen_enums.py from contracts/openapi.yaml. DO NOT EDIT.
--
-- Every Postgres enum below is derived mechanically from the wire contract, so
-- "the database enum agrees with the contract enum" is a property of the build
-- rather than a claim in a comment. tools/check_enums.py re-verifies it against
-- a live database in CI.
--
-- Contract enums with no persisted counterpart are listed in
-- tools/enum_map.py:EXCLUSIONS, each with a reason.

-- +goose Up
"""

FOOTER_UP = "\n-- +goose Down\n"


def q(label):
    return "'" + str(label).replace("'", "''") + "'"


def main():
    found = contract_enums()
    missing = [c for c in list(MAPPED) + list(MAPPED_IN_MIGRATION) if c not in found]
    if missing:
        raise SystemExit("contract enums named in enum_map but absent from openapi.yaml: %r" % missing)
    unknown = [c for c in found
               if c not in MAPPED and c not in MAPPED_IN_MIGRATION and c not in EXCLUSIONS]
    if unknown:
        raise SystemExit(
            "contract enums with neither a mapping nor an exclusion: %r\n"
            "Add each to tools/enum_map.py." % unknown
        )

    out = [HEADER]
    for contract_name in sorted(MAPPED, key=lambda k: MAPPED[k]):
        pg = MAPPED[contract_name]
        labels = [v for v in found[contract_name] if v is not None]
        out.append("-- %s  <-  %s" % (pg, contract_name))
        out.append("CREATE TYPE %s AS ENUM (" % pg)
        out.append("  " + ",\n  ".join(q(v) for v in labels))
        out.append(");")
        out.append("")

    out.append(FOOTER_UP)
    for contract_name in sorted(MAPPED, key=lambda k: MAPPED[k], reverse=True):
        out.append("DROP TYPE IF EXISTS %s;" % MAPPED[contract_name])
    out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
