#!/usr/bin/env node
// Writes the device-lab GPX routes in this folder, one point per second.
//
//   node tools/e2e/native/routes/build-routes.mjs           write them
//   node tools/e2e/native/routes/build-routes.mjs --check   fail if a committed file differs
//
// The points are the devworld ones, so a route on the emulator matches what the API knows:
//   - Bismillah Grill's door, 1240 Danforth Avenue: services/hg/internal/devworld/catalogue.go
//     and route.go (restaurantPoint) — 43.6815, -79.3310
//   - Amina's home pin: migrations/devworld/001_personas.sql and route.go (customerPoint) —
//     43.6825, -79.3300
//   - the short pickup start (shortStart) 43.6842, -79.3310, and the long one (longStart
//     43.6815, -79.3460, via longBend 43.6760, -79.3390): route.go
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const START = Date.parse('2026-10-10T16:00:00Z');

const P = {
  restaurant: [43.6815, -79.3310],
  amina: [43.6825, -79.3300],
  danforthCorner: [43.6815, -79.3300], // east along Danforth to the corner, then north to Amina
  shortStart: [43.6842, -79.3310],
  longStart: [43.6815, -79.3460],
  longBend: [43.6760, -79.3390],
};

const metres = ([la1, lo1], [la2, lo2]) => {
  const k = Math.PI / 180;
  const x = (lo2 - lo1) * k * Math.cos(((la1 + la2) / 2) * k);
  const y = (la2 - la1) * k;
  return Math.hypot(x, y) * 6371000;
};

/**
 * Build a route from segments. Each segment is one of:
 *   { to: [lat, lon], speed: m/s }   move in a straight line, one point per second
 *   { dwell: s }                     stay put, still one point per second
 *   { stall: s }                     no point at all for s seconds (the device stops reporting)
 */
function route(from, segments) {
  const pts = [{ at: from, t: 0 }];
  let here = from;
  let t = 0;
  for (const seg of segments) {
    if (seg.to) {
      const steps = Math.max(1, Math.round(metres(here, seg.to) / seg.speed));
      for (let i = 1; i <= steps; i++) {
        const f = i / steps;
        t += 1;
        pts.push({ at: [here[0] + (seg.to[0] - here[0]) * f, here[1] + (seg.to[1] - here[1]) * f], t });
      }
      here = seg.to;
    } else if (seg.dwell) {
      for (let i = 0; i < seg.dwell; i++) pts.push({ at: here, t: ++t });
    } else if (seg.stall) {
      t += seg.stall;
    }
  }
  return pts;
}

function gpx(name, desc, pts) {
  const lines = pts.map(({ at: [lat, lon], t }) =>
    `      <trkpt lat="${lat.toFixed(6)}" lon="${lon.toFixed(6)}"><time>${new Date(START + t * 1000).toISOString().replace('.000Z', 'Z')}</time></trkpt>`);
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by build-routes.mjs in this folder. Edit that file, not this one. -->',
    '<gpx version="1.1" creator="hg-mono tools/e2e/native/routes/build-routes.mjs" xmlns="http://www.topografix.com/GPX/1/1">',
    `  <metadata><name>${name}</name><desc>${desc}</desc></metadata>`,
    '  <trk>',
    `    <name>${name}</name>`,
    '    <trkseg>',
    ...lines,
    '    </trkseg>',
    '  </trk>',
    '</gpx>',
    '',
  ].join('\n');
}

const ROUTES = {
  'restaurant-to-amina': {
    desc: 'Dropoff leg: Bismillah Grill (1240 Danforth Ave) to Amina\'s home pin, by bike at about 5 m/s, east along Danforth then north. About 45 s.',
    pts: route(P.restaurant, [{ dwell: 3 }, { to: P.danforthCorner, speed: 5 }, { to: P.amina, speed: 5 }, { dwell: 5 }]),
  },
  'rider-to-restaurant': {
    desc: 'Pickup leg, the devworld short route: from 300 m north of Bismillah Grill (route.go shortStart) to its door, at about 5 m/s. About 70 s.',
    pts: route(P.shortStart, [{ dwell: 3 }, { to: P.restaurant, speed: 5 }, { dwell: 5 }]),
  },
  'rider-long-stall': {
    desc: 'Pickup leg, the devworld long route (route.go longStart, longBend, restaurantPoint) at about 6 m/s, with no fix at all for 120 s at the bend: longer than dispatch\'s 90 s freshness window. About 7 min.',
    pts: route(P.longStart, [{ dwell: 3 }, { to: P.longBend, speed: 6 }, { dwell: 2 }, { stall: 120 }, { dwell: 2 }, { to: P.restaurant, speed: 6 }, { dwell: 5 }]),
  },
};

const check = process.argv.includes('--check');
let stale = 0;
for (const [name, r] of Object.entries(ROUTES)) {
  const file = join(HERE, `${name}.gpx`);
  const body = gpx(name, r.desc, r.pts);
  if (check) {
    if (!existsSync(file) || readFileSync(file, 'utf8') !== body) {
      console.error(`stale: ${name}.gpx (run node tools/e2e/native/routes/build-routes.mjs)`);
      stale++;
    }
  } else {
    writeFileSync(file, body);
    console.log(`${name}.gpx  ${r.pts.length} points, ${r.pts.at(-1).t} s`);
  }
}
if (stale) process.exit(1);
