/**
 * Exports every template to static files the Go service embeds:
 *
 *   services/hg/internal/notify/emailtmpl/templates/<name>.html
 *   services/hg/internal/notify/emailtmpl/templates/<name>.txt
 *   services/hg/internal/notify/emailtmpl/templates/manifest.json
 *
 * The output is committed, so the Go binary builds and runs with no Node at
 * all. `--check` renders in memory and fails when the committed files are stale,
 * which is how CI catches a template edited without re-exporting
 * (`pnpm --filter @hg/emails build:check`).
 *
 * Usage: pnpm --filter @hg/emails build [--check]
 */
import { mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { render } from '@react-email/components';

import { slotsIn } from './define.js';
import { templates } from './registry.js';

const here = dirname(fileURLToPath(import.meta.url));
/** Where the exported files go: the Go package that embeds them. */
export const outDir = resolve(here, '../../../services/hg/internal/notify/emailtmpl/templates');

/** One template as exported: its subject, declared vars, and both message parts. */
export interface ExportedTemplate {
  name: string;
  subject: string;
  vars: string[];
  html: string;
  text: string;
}

/**
 * Headings keep their case in the plain-text part; html-to-text upper-cases
 * them by default, which would also upper-case a slot name inside one. React
 * Email appends these to its own selectors (images and preview text skipped,
 * links printed without brackets).
 */
const textSelectors = [
  ...['h1', 'h2', 'h3'].map((selector) => ({
    selector,
    options: { uppercase: false, leadingLineBreaks: 1, trailingLineBreaks: 2 },
  })),
];

/** Renders every template and checks its slots against its declared vars. */
export async function exportAll(): Promise<ExportedTemplate[]> {
  const out: ExportedTemplate[] = [];
  const names = new Set<string>();
  for (const t of templates) {
    if (names.has(t.name)) throw new Error(`template name "${t.name}" is used twice`);
    names.add(t.name);

    const element = t.element();
    const html = await render(element, { pretty: true });
    const text = (await render(element, { plainText: true, htmlToTextOptions: { selectors: textSelectors } })).trim() + '\n';
    const subject = t.subject;
    if (/[\r\n]/.test(subject)) throw new Error(`${t.name}: the subject must be one line`);

    // Every declared var is used, and nothing undeclared is: a slot the Go
    // caller does not know about would fail to render, and a declared var no
    // template uses is a builder computing something nobody reads.
    const used = new Set([...slotsIn(html), ...slotsIn(text), ...slotsIn(subject)]);
    const declared = new Set<string>(t.vars);
    const undeclared = [...used].filter((v) => !declared.has(v));
    const unused = [...declared].filter((v) => !used.has(v));
    if (undeclared.length || unused.length) {
      throw new Error(
        `${t.name}: slots used but not declared [${undeclared.join(', ')}], declared but not used [${unused.join(', ')}]`,
      );
    }
    // Any other `{{` would be parsed by Go's template engine as an action.
    const stray = (html + text + subject).replace(/\{\{\s*\.[A-Za-z0-9_]+\s*\}\}/g, '');
    if (stray.includes('{{') || stray.includes('}}')) {
      throw new Error(`${t.name}: contains a "{{" or "}}" that is not a {{.Var}} slot`);
    }

    out.push({ name: t.name, subject, vars: [...t.vars], html, text });
  }
  return out;
}

function files(exported: ExportedTemplate[]): Map<string, string> {
  const m = new Map<string, string>();
  for (const t of exported) {
    m.set(`${t.name}.html`, t.html);
    m.set(`${t.name}.txt`, t.text);
  }
  const manifest = {
    $comment:
      'GENERATED by `pnpm --filter @hg/emails build` from packages/emails. Do not edit; change the React template and re-export.',
    templates: exported.map(({ name, subject, vars }) => ({ name, subject, vars })),
  };
  m.set('manifest.json', JSON.stringify(manifest, null, 2) + '\n');
  return m;
}

async function main() {
  const check = process.argv.includes('--check');
  const wanted = files(await exportAll());

  let existing: string[] = [];
  try {
    existing = readdirSync(outDir);
  } catch {
    existing = [];
  }

  if (check) {
    const problems: string[] = [];
    for (const [name, content] of wanted) {
      let onDisk: string | null = null;
      try {
        onDisk = readFileSync(join(outDir, name), 'utf8');
      } catch {
        onDisk = null;
      }
      if (onDisk === null) problems.push(`missing: ${name}`);
      else if (onDisk !== content) problems.push(`stale: ${name}`);
    }
    for (const name of existing) if (!wanted.has(name)) problems.push(`not exported by any template: ${name}`);
    if (problems.length) {
      console.error(
        `email templates are out of date with packages/emails:\n  ${problems.join('\n  ')}\n` +
          'Run: pnpm --filter @hg/emails build',
      );
      process.exit(1);
    }
    console.log(`email templates: ${wanted.size} files up to date`);
    return;
  }

  mkdirSync(outDir, { recursive: true });
  for (const name of existing) if (!wanted.has(name)) unlinkSync(join(outDir, name));
  for (const [name, content] of wanted) writeFileSync(join(outDir, name), content);
  console.log(`email templates: wrote ${wanted.size} files to ${outDir}`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err: unknown) => {
    console.error(err);
    process.exit(1);
  });
}
